fabric-testbed/fabric-docker-images

jupyter-notebook/0.0.1/Dockerfile
jupyter-notebook/0.0.1/docker-entrypoint.sh
jupyter-notebook/0.0.1/requirements.txt
jupyter-notebook/README.md
jupyterhub-k8s/0.9.0/Dockerfile
jupyterhub-k8s/0.9.0/requirements.txt
jupyterhub-k8s/README.md

As title. The images will be used for JupyterHub deployment.

JupyterHub and Jupyter Notebook images

---

postgres/12.3/Dockerfile
postgres/12.3/create_multiple_db.sh
postgres/Readme.md

- Postgres image allowing multiple databases in same container

Postgres image allowing multiple databases in same container

---

authzforce-pdp/3.1.0/Dockerfile
authzforce-pdp/3.1.0/README.md
authzforce-pdp/3.1.0/conf/README
authzforce-pdp/3.1.0/conf/application.yml
authzforce-pdp/3.1.0/conf/catalog.xml
authzforce-pdp/3.1.0/conf/logback.xml
authzforce-pdp/3.1.0/conf/pdp-ext.xsd
authzforce-pdp/3.1.0/conf/pdp.xml
authzforce-pdp/3.1.0/conf/spring-beans.xml
authzforce-pdp/3.1.0/docker-entrypoint.sh
authzforce-pdp/3.1.0/policies/ExampleProjPolicy.xml
authzforce-pdp/3.1.0/policies/ExampleProjRequest.xml

with RESTful server 3.1.0 and command line tools 16.0.0
https://github.com/authzforce/restful-pdp
No changes other than version updates on the jars.

Updated version of AuthZ PDP 

---

vouch-proxy/0.27.1/Dockerfile
vouch-proxy/Readme.md

https://github.com/fabric-testbed/fabric-docker-images/issues/5

Vouch Proxy Image

---

jupyter-notebook/0.0.10/Dockerfile
jupyter-notebook/0.0.10/docker-entrypoint.sh
jupyter-notebook/0.0.10/jupyter_startup.py
jupyter-notebook/0.0.10/requirements.txt

https://github.com/fabric-testbed/fabric-docker-images/issues/8

notebook image - cli version and startup script

---

jupyter-notebook/1.1.0/Dockerfile
jupyter-notebook/1.1.0/docker-entrypoint.sh
jupyter-notebook/1.1.0/jupyter_startup.py
jupyter-notebook/1.1.0/requirements.txt

- adding Vim to the updated base image

16 jupyter notebook

---

jupyter-notebook/1.1.1/Dockerfile
jupyter-notebook/1.1.1/docker-entrypoint.sh
jupyter-notebook/1.1.1/jupyter_startup.py
jupyter-notebook/1.1.1/requirements.txt

[#16] restrict matplotlib to v3.3.4

---

jupyter-notebook/1.1.2/Dockerfile
jupyter-notebook/1.1.2/docker-entrypoint.sh
jupyter-notebook/1.1.2/jupyter_startup.py
jupyter-notebook/1.1.2/requirements.txt

image for rel 1.1

---

jupyter-notebook/1.2.1/Dockerfile
jupyter-notebook/1.2.1/docker-entrypoint.sh
jupyter-notebook/1.2.1/jupyter_startup.py
jupyter-notebook/1.2.1/requirements.txt

- updated notebook image to use latest CLI and FABLIB
- Modified the startup script to setup fabric_config with a default fabric_rc with the required environment variable
- Clone the JH examples using a tag

updated notebook image to use latest CLI and FABLIB

---

jupyter-notebook/1.2.2/Dockerfile
jupyter-notebook/1.2.2/docker-entrypoint.sh
jupyter-notebook/1.2.2/jupyter_startup.py
jupyter-notebook/1.2.2/requirements.txt

- 1.2 fabrictestbed-extensions and change the default jupyter-examples tag to 1.2

changes for release 1.2

---

jupyter-notebook/1.2.4/Dockerfile
jupyter-notebook/1.2.4/docker-entrypoint.sh
jupyter-notebook/1.2.4/jupyter_startup.py
jupyter-notebook/1.2.4/requirements.txt

- JH Notebook image with 1.2.1 fabrictestbed-extensions

JH Notebook image with 1.2.1 fabrictestbed-extensions

---

jupyter-notebook/1.2.5/Dockerfile
jupyter-notebook/1.2.5/docker-entrypoint.sh
jupyter-notebook/1.2.5/jupyter_startup.py
jupyter-notebook/1.2.5/requirements.txt

JH image update 
- Updated default fabric_rc to include the default log level and log file to avoid observing the WARNING traces on stdout

fix for the warning log by configuring default log file

---

authzforce-pdp/6.0.1/Dockerfile
authzforce-pdp/6.0.1/README.md
authzforce-pdp/6.0.1/conf/README
authzforce-pdp/6.0.1/conf/application.yml
authzforce-pdp/6.0.1/conf/catalog.xml
authzforce-pdp/6.0.1/conf/logback.xml
authzforce-pdp/6.0.1/conf/pdp-ext.xsd
authzforce-pdp/6.0.1/conf/pdp.xml
authzforce-pdp/6.0.1/conf/spring-beans.xml
authzforce-pdp/6.0.1/docker-entrypoint.sh
authzforce-pdp/6.0.1/policies/ExampleProjPolicy.xml
authzforce-pdp/6.0.1/policies/ExampleProjRequest.xml

Ready to be built in Docker Hub

Updating to PDP 6.0.1/CLI20

---

jupyter-notebook/1.3.0/Dockerfile
jupyter-notebook/1.3.0/docker-entrypoint.sh
jupyter-notebook/1.3.0/jupyter_startup.py
jupyter-notebook/1.3.0/requirements.txt

Release 1.3.0

---

neo4j-apoc/5.3.0/Dockerfile
neo4j-apoc/5.3.0/README.md
neo4j-apoc/5.3.0/apoc.conf
neo4j-apoc/5.3.0/aux/README.md
neo4j-apoc/5.3.0/aux/docker-entrypoint.sh
neo4j-apoc/5.3.0/aux/migrate.sh
neo4j-apoc/5.3.0/aux/migration-notes.md
neo4j-apoc/5.3.0/aux/neo4j.conf
neo4j-apoc/5.3.0/aux/neo4jlabs-plugins.json
neo4j-apoc/README.md

This is to be used with CF 1.5 and above. Still requires lots of testing especially for the migration script.

Added a version of Neo4j/APOC/GDS docker version 5.3.0 also with a mgration script

---

jupyterhub-k8s/1.3.0/Dockerfile
jupyterhub-k8s/1.3.0/requirements.txt

update fabricauthenticator version

update fabricauthenticator version

---

user_local_jupyter_environment/0.0.1/Dockerfile
user_local_jupyter_environment/README.md

This is an initial docker image PR  for an  image that provides a full jupyterlab environment on a users laptop.  
@mjstealey I think you will need to initialize dockerhub for this new image 
(note: there is a second PR for another new image)

Fablib env

---

slice-vm-rocky8-multitool/0.0.1/Dockerfile
slice-vm-rocky8-multitool/0.0.1/extra/tools/frr_config.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/frr_config_docker.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/host_config.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/host_config_redhat.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/host_tune_redhat.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/host_tune_ubuntu.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/iperf3_client.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/iperf3_server.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/iperf3_server_persistent.sh
slice-vm-rocky8-multitool/0.0.1/extra/tools/node_exporter/LICENSE
slice-vm-rocky8-multitool/0.0.1/extra/tools/node_exporter/NOTICE
slice-vm-rocky8-multitool/0.0.1/extra/tools/process_iperf_data.py
slice-vm-rocky8-multitool/README.md

This is an initial docker image PR  for an  image that provides many tools commonly needed in fabric slices.  
@mjstealey I think you will need to initialize dockerhub for this new image 
(note: there is a second PR for another new image)

added initial rocky8 multitool image for user vms

---

slice-vm-rocky8-multitool/0.0.2/Dockerfile

added rocky8 multitool 0.0.2

---

jupyter-notebook/3.0.0/Dockerfile
jupyter-notebook/3.0.0/docker-entrypoint.sh
jupyter-notebook/3.0.0/jupyter_notebook_config.py
jupyter-notebook/3.0.0/profile.sh
jupyter-notebook/3.0.0/requirements.txt

update base image to single_user:3.0.0

update base image to single_user:3.0.0

---

jupyter-notebook/3.0.0/Dockerfile

remove explicit install of labextensions as recommended for JupyterLab 3

remove explicit install of labextensions as recommended for JupyterLab 3

---

jupyter-notebook/3.0.0/requirements.txt

- Update Fablib
- Include mflib and slicecommander
- Update Chi dependencies

Update FALL container

---

jupyterhub-k8s/2.0.1/Dockerfile
jupyterhub-k8s/2.0.1/requirements.txt

Pick newer version of fabricauthenticator enabled to handle cookies with only sub claim

Pick newer version of fabricauthenticator

---

timestamp/0.1.2/Dockerfile

updated ptp timestamp tutorial for knit 7

timestamp tutorial for knit7

---

authzforce-pdp/6.1.0/Dockerfile
authzforce-pdp/6.1.0/README.md
authzforce-pdp/6.1.0/conf/README
authzforce-pdp/6.1.0/conf/application.yml
authzforce-pdp/6.1.0/conf/catalog.xml
authzforce-pdp/6.1.0/conf/logback.xml
authzforce-pdp/6.1.0/conf/pdp-ext.xsd
authzforce-pdp/6.1.0/conf/pdp.xml
authzforce-pdp/6.1.0/conf/spring-beans.xml
authzforce-pdp/6.1.0/docker-entrypoint.sh
authzforce-pdp/6.1.0/policies/ExampleProjPolicy.xml
authzforce-pdp/6.1.0/policies/ExampleProjRequest.xml

Added version 6.1.0 of authzforce PDP container

---

user_local_jupyter_environment/1.7.0/docker-compose.yml

only listen on 127.0.0.1 to restrict connections on localhost

only listen on 127.0.0.1 to restrict connections on localhost

---

jupyter-notebook/1.8.0/Dockerfile

small change to force jenkins to create image

small change to force jenkins to create image

---

jupyter-notebook/1.9.0/Dockerfile
jupyter-notebook/1.9.0/release.txt
jupyter-notebook/1.9.0/requirements.txt

update fablib version and release name

update fablib version and release name
